// Code generated by protoc-gen-zig
///! package protos
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const Announcement = struct {
    ts: u64 = 0,
    catalog: u32 = 0,
    title: ManagedString = .Empty,
    call_to_action: bool = false,
    tokens: ArrayList(ManagedString),
    signature: ManagedString = .Empty,

    pub const _desc_table = .{
        .ts = fd(1, .{ .Varint = .Simple }),
        .catalog = fd(2, .{ .Varint = .Simple }),
        .title = fd(3, .String),
        .call_to_action = fd(4, .{ .Varint = .Simple }),
        .tokens = fd(5, .{ .List = .String }),
        .signature = fd(6, .Bytes),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
