// Code generated by protoc-gen-zig
///! package protos
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const Announcement = struct {
    ts: u64 = 0,
    signature: ManagedString = .Empty,
    tokens: ArrayList(ManagedString),

    pub const _desc_table = .{
        .ts = fd(1, .{ .Varint = .Simple }),
        .signature = fd(2, .Bytes),
        .tokens = fd(3, .{ .List = .String }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
