# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: all.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'all.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tall.proto\x12\x06protos\"u\n\x0c\x41nnouncement\x12\n\n\x02ts\x18\x01 \x01(\x04\x12\x0f\n\x07\x63\x61talog\x18\x02 \x01(\r\x12\r\n\x05title\x18\x03 \x01(\t\x12\x16\n\x0e\x63\x61ll_to_action\x18\x04 \x01(\x08\x12\x0e\n\x06tokens\x18\x05 \x03(\t\x12\x11\n\tsignature\x18\x06 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'all_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANNOUNCEMENT']._serialized_start=21
  _globals['_ANNOUNCEMENT']._serialized_end=138
# @@protoc_insertion_point(module_scope)
